### ISSUE TITLE
Which version of cisBP pwm to use with chromVAR?

### ISSUE THREAD

**Issue by biobenkj** [GreenleafLab/chromVARmotifs#2]
Thank you for writing a great piece of software and adding in the cisBP data! A quick question, which version should be used with chromVAR? v1 or v2?

Thanks!

**Comment by caleblareau** [comment]
Both should be totally fine— v1 was designed to be more comprehensive. v2 is a proper subset. When doing dimensionality reduction, etc., we (or at least I) found that the v1 had too much redundancy at times, which was at least partially solved in v2. Depending on what you want to achieve, either could be used. I’d recommend v2 personally.

**Comment by biobenkj** [comment]
Thanks! Feel free to close.
